# Generated by Django 2.1.15 on 2020-11-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0013_auto_20201001_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata_archive',
            name='contacts',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
