# Generated by Django 2.1.15 on 2020-12-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0015_activelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata_activity',
            old_name='date',
            new_name='latest_service',
        ),
    ]
