# Generated by Django 3.1.1 on 2021-03-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0016_auto_20201201_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('service_repair', models.CharField(blank=True, max_length=100, null=True)),
                ('active_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('report_data', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
