# Generated by Django 2.1.15 on 2021-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0018_reportfile_equipment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata_archive',
            name='active_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
