# Generated by Django 2.1.15 on 2022-03-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0019_metadata_archive_active_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata_main',
            name='department_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
